window.HOPE_DATA = {
  "timeline": [
    {
      "id": "edu-nit-calicut",
      "type": "education",
      "date_start": "2016-08",
      "date_end": "2020-05",
      "label": "BTech ECE @ NIT Calicut",
      "org": "NIT Calicut",
      "domain": "nitc.ac.in",
      "metric": null,
      "skills": ["Systems Thinking", "Signal Processing"],
      "pane": "education",
      "anchor": "tl-edu-nit-calicut"
    },
    {
      "id": "exp-novartis",
      "type": "experience",
      "date_start": "2020-08",
      "date_end": "2022-07",
      "label": "Analyst @ Novartis",
      "org": "Novartis Healthcare",
      "domain": "novartis.com",
      "metric": "10% ROI increase",
      "skills": ["Python", "SQL", "D3.js", "Statistical Analysis"],
      "pane": "experience",
      "anchor": "tl-exp-novartis"
    },
    {
      "id": "edu-uiowa",
      "type": "education",
      "date_start": "2022-08",
      "date_end": "2024-05",
      "label": "MSBA @ University of Iowa",
      "org": "University of Iowa",
      "domain": "uiowa.edu",
      "metric": "100% NSF scholarship",
      "skills": ["Statistical Analysis", "Python", "R"],
      "pane": "education",
      "anchor": "tl-edu-uiowa"
    },
    {
      "id": "exp-iowa-research",
      "type": "experience",
      "date_start": "2022-08",
      "date_end": "2024-05",
      "label": "NSF Researcher @ Iowa",
      "org": "University of Iowa",
      "domain": "uiowa.edu",
      "metric": "700M rows · 80% faster",
      "skills": ["PySpark", "Statistical Analysis", "Python"],
      "pane": "experience",
      "anchor": "tl-exp-iowa-research"
    },
    {
      "id": "cert-az900",
      "type": "certification",
      "date_start": "2023-12",
      "date_end": "2023-12",
      "label": "AZ-900 Azure Fundamentals",
      "org": "Microsoft",
      "domain": "microsoft.com",
      "metric": null,
      "skills": ["Azure"],
      "pane": "certifications",
      "anchor": "tl-cert-az900"
    },
    {
      "id": "exp-careerx",
      "type": "experience",
      "date_start": "2024-05",
      "date_end": "2024-12",
      "label": "Founder & CTO @ CareerX",
      "org": "CareerX",
      "domain": "careerx.app",
      "metric": "$250K Microsoft credits",
      "skills": ["LangChain", "RAG Pipelines", "Graph DB", "Azure OpenAI"],
      "pane": "experience",
      "anchor": "tl-exp-careerx"
    },
    {
      "id": "proj-careerx-platform",
      "type": "project",
      "date_start": "2024-05",
      "date_end": "2024-12",
      "label": "CareerX AI Platform",
      "org": "CareerX",
      "domain": "careerx.app",
      "metric": "90% error reduction",
      "skills": ["LangChain", "RAG", "Graph DB"],
      "pane": "projects",
      "anchor": "tl-proj-careerx-platform"
    },
    {
      "id": "exp-ey",
      "type": "experience",
      "date_start": "2025-01",
      "date_end": null,
      "label": "Lead AI Engineer @ EY",
      "org": "EY",
      "domain": "ey.com",
      "metric": "$2M+ pipeline · 5 to prod",
      "skills": ["Autogen", "MCP", "Unitree GO2", "Claude Code"],
      "pane": "experience",
      "anchor": "tl-exp-ey"
    },
    {
      "id": "proj-ai-image-gen",
      "type": "project",
      "date_start": "2025-01",
      "date_end": "2025-01",
      "label": "AI Image Gen App",
      "org": "EY",
      "domain": "ey.com",
      "metric": "100K+ users · 11 days",
      "skills": ["FastAPI", "React", "Azure OpenAI"],
      "pane": "projects",
      "anchor": "tl-proj-ai-image-gen"
    },
    {
      "id": "proj-enterprise-platform",
      "type": "project",
      "date_start": "2025-01",
      "date_end": null,
      "label": "Enterprise Agent Platform",
      "org": "EY",
      "domain": "ey.com",
      "metric": "15+ repos contributed",
      "skills": ["LangGraph", "A2A", "Kubernetes"],
      "pane": "projects",
      "anchor": "tl-proj-enterprise-platform"
    },
    {
      "id": "proj-autonomous-inspection",
      "type": "project",
      "date_start": "2025-01",
      "date_end": null,
      "label": "Autonomous Inspection Platform",
      "org": "EY",
      "domain": "ey.com",
      "metric": "$2M+ pipeline",
      "skills": ["Unitree GO2", "ROS2", "Azure OpenAI"],
      "pane": "projects",
      "anchor": "tl-proj-autonomous-inspection"
    },
    {
      "id": "proj-art-of-living",
      "type": "project",
      "date_start": "2025-02",
      "date_end": "2025-04",
      "label": "Art of Living AI Assistant",
      "org": "Art of Living Foundation",
      "domain": "artofliving.org",
      "metric": "500M+ potential users",
      "skills": ["MCP", "RAG", "FastAPI"],
      "pane": "projects",
      "anchor": "tl-proj-art-of-living"
    },
    {
      "id": "proj-multi-agent-engine",
      "type": "project",
      "date_start": "2025-01",
      "date_end": "2025-03",
      "label": "Multi-Agent Workflow Engine",
      "org": "EY",
      "domain": "ey.com",
      "metric": "3 wks → 2 days",
      "skills": ["Autogen", "MCP", "Multi-Agent", "Python"],
      "pane": "projects",
      "anchor": "tl-proj-multi-agent-engine"
    },
    {
      "id": "proj-clinical-trial",
      "type": "project",
      "date_start": "2024-10",
      "date_end": "2024-10",
      "label": "Clinical Trial Matching Engine",
      "org": null,
      "domain": null,
      "metric": "Prod-grade accuracy",
      "skills": ["RAG", "NER", "SciSpacy", "Python"],
      "pane": "projects",
      "anchor": "tl-proj-clinical-trial"
    }
  ],
  "traveler": "rocket"
};
